name: Ubuntu
on:
  watch:
    types: started
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection to Actions
      uses: Hzlarm/debugger-action@master
#      uses: P3TERX/debugger-action@master
